import type { PancoData, Transaction } from './types.ts';
export function demoData(): PancoData {
  const month = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Bahia',
    year: 'numeric',
    month: '2-digit',
  }).format(new Date());
  const date = (d: number) => `${month}-${String(d).padStart(2, '0')}`;
  const tx = (
    id: string,
    name: string,
    amount: string,
    day: number,
    category: string,
    extra: Partial<Transaction> = {},
  ): Transaction => ({
    id,
    account_id: 'bank',
    card_id: null,
    invoice_id: null,
    category_id: category,
    description: name,
    merchant_name: name,
    merchant_key: name.toLowerCase(),
    amount,
    direction: 'expense',
    status: 'posted',
    source: 'manual',
    occurred_at: date(day) + 'T12:00:00Z',
    due_date: date(day),
    installment_number: null,
    total_installments: null,
    defer_to_next_month: false,
    needs_review: false,
    kind: 'regular',
    currency: 'BRL',
    ...extra,
  });
  return {
    accounts: [
      {
        id: 'bank',
        name: 'Conta principal',
        current_balance: '8350.00',
        currency: 'BRL',
        include_in_forecast: true,
        balance_as_of: date(5) + 'T12:00:00Z',
        kind: 'checking',
      },
    ],
    cards: [
      {
        id: 'card',
        name: 'Meu cartão',
        brand: 'Mastercard',
        last_four: '4829',
        total_limit: '15000.00',
        available_limit: '12180.00',
        closing_day: 25,
        due_day: 5,
        payment_account_id: 'bank',
        currency: 'BRL',
      },
    ],
    categories: [
      { id: 'food', name: 'Alimentação', kind: 'expense', color: '#6E8C6A', icon: 'utensils' },
      { id: 'home', name: 'Moradia', kind: 'expense', color: '#B49175', icon: 'house' },
      { id: 'transport', name: 'Transporte', kind: 'expense', color: '#8C9FA8', icon: 'car' },
      { id: 'leisure', name: 'Lazer', kind: 'expense', color: '#B29A73', icon: 'sparkles' },
      { id: 'salary', name: 'Salário', kind: 'income', color: '#0F3B2E', icon: 'briefcase' },
      {
        id: 'subscriptions',
        name: 'Assinaturas',
        kind: 'expense',
        color: '#8D82A1',
        icon: 'repeat',
      },
    ],
    transactions: [
      tx('1', 'Salário', '12500.00', 1, 'salary', { direction: 'income' }),
      tx('2', 'Mercado da esquina', '248.90', 3, 'food'),
      tx('3', 'iFood', '68.50', 4, 'food'),
      tx('4', 'Café do bairro', '24.00', 5, 'food'),
      tx('5', 'Aluguel', '2200.00', 10, 'home', { status: 'pending' }),
      tx('6', 'Projeto freelance', '1800.00', 20, 'salary', {
        status: 'pending',
        direction: 'income',
      }),
      tx('7', 'Livraria', '129.90', 4, 'leisure', {
        account_id: null,
        card_id: 'card',
        invoice_id: 'invoice',
        installment_number: 2,
        total_installments: 3,
      }),
      tx('8', 'Uber', '32.40', 5, 'transport'),
      tx('9', 'Internet', '119.90', 15, 'home', { status: 'pending' }),
      tx('10', 'Netflix', '39.90', 12, 'subscriptions', { status: 'pending' }),
    ],
    invoices: [
      {
        id: 'invoice',
        card_id: 'card',
        due_date: date(8),
        closing_date: date(1),
        status: 'CLOSED',
        remaining_due: '2820.00',
        reported_total: '2820.00',
        estimated_total: '129.90',
        total_paid: '0.00',
      },
    ],
    subscriptions: [
      {
        id: 'netflix',
        name: 'Netflix',
        amount: '39.90',
        interval_unit: 'month',
        interval_count: 1,
        next_due_date: date(12),
        status: 'active',
        account_id: 'bank',
        card_id: null,
      },
      {
        id: 'spotify',
        name: 'Spotify',
        amount: '21.90',
        interval_unit: 'month',
        interval_count: 1,
        next_due_date: date(18),
        status: 'active',
        account_id: null,
        card_id: 'card',
      },
      {
        id: 'gym',
        name: 'Smart Fit',
        amount: '139.90',
        interval_unit: 'month',
        interval_count: 1,
        next_due_date: date(22),
        status: 'active',
        account_id: null,
        card_id: 'card',
      },
    ],
    investments: [
      {
        id: 'inv1',
        name: 'Tesouro IPCA+',
        asset_class: 'fixed_income',
        current_value: '18450.00',
        cost_basis: '17000.00',
      },
      {
        id: 'inv2',
        name: 'Carteira de FIIs',
        asset_class: 'reit',
        current_value: '6800.00',
        cost_basis: '6500.00',
      },
    ],
    investment_income: [
      {
        id: 'yield',
        investment_id: 'inv2',
        payment_date: date(15),
        net_amount: '62.40',
        kind: 'distribution',
        status: 'paid',
      },
    ],
    forecast: {
      current_balance: '8350.00',
      pending_income: '1800.00',
      pending_expenses: '2359.80',
      invoices_due: '2820.00',
      projected_balance: '4970.20',
      review_count: 0,
      missing_balance_count: 0,
      as_of: date(5) + 'T12:00:00Z',
      through: date(28),
    },
  };
}
